### ISSUE TITLE
WiNLEM path required on Mac

### ISSUE THREAD

**Issue by edydkim** [mjfwalsh/Lemmini#1]
Hi there, 
Thank you for sharing.
I like to compile and run it on the following environment, but the dialogue came up to require some inputs below.
It would be great if it could help us with that.

- Environment
```
macOS Monterey
Version 12.6
Chip Apple M1 Pro
Memory 32 GB
```

- Console
```shell
$ ./make.sh jar 
Running Java Compiler...
Making Jar File...
$ ./make.sh install
Making Mac App...
Installing Mac App...
```

- Dialogue
<img width="424" alt="Screen Shot 2022-10-23 at 14 57 06" src="https://user-images.githubusercontent.com/1640053/197376506-06e464ba-539f-43d5-80f1-f2956b4ecb5e.png">

**Comment by mjfwalsh** [comment]
Hi Edward,

Lemmini doesn't actually come with the graphics or level information required to play Lemmings, as these are still under copyright.

It can however extract the  graphics and level information from a copy of "Lemmings for Windows". It's just prompting you for the directory where that copy is.

This is explained in the disclaimer window just before you see the above prompt box.

I never read the legal stuff either.

Regards,

Michael

**Comment by edydkim** [comment]
Hi Michael,

Thank you for the explanation.

I understand it's still under copyright; Please let me take a look at the "Lemmings for Windows", either!

Best regards,
Eddie
